defaults: {}
queue_rules:
  - name: default
    conditions: []
pull_request_rules:
  - name: Automatically merge successful Scala Steward PRs
    conditions:
      - or:
          - author=scala-steward
          - author=slick-scala-steward[bot]
          - author=renovate[bot]
      - check-success=Build and Test (ubuntu-latest, 2.12.18, temurin@8)
    actions:
        queue:
            name: default
